name: habit_quest
description: "Gamified Habit Tracker App."

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  appwrite: ^13.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  go_router: ^14.6.2
  lottie: ^3.2.0
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  carousel_slider_plus: ^7.1.0
  flutter_calendar_carousel: ^2.4.4
  fl_chart: ^0.69.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banana/
    - assets/images/achievements/
    - assets/images/temp/
    - assets/lottie/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
