name: habit_quest
description: "Gamified Habit Tracker App."

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  appwrite: ^13.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  go_router: ^14.6.2
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  carousel_slider_plus: ^7.1.0
  fl_chart: ^0.69.2
  flutter_animate: ^4.5.2
  hive_ce: ^2.8.0+3
  hive_ce_flutter: ^2.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_analytics: ^11.4.0
  cloud_firestore: ^5.6.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.1
  integration_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banana/
    - assets/images/achievements/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
