name: habit_quest
description: "Gamified Habit Tracker App."

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  appwrite: ^13.1.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  lottie: ^3.2.0
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

flutter_native_splash:
  # dart run flutter_native_splash:create
  # dart run flutter_native_splash:remove
  color: "#0066cc"
  image: app_resources/white_logo.png
  color_web: "#0066cc"
  image_web: app_resources/white_logo.png
  android_12:
    color: "#0066cc"
