// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habit_quest/repositories/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(HabitFrequencyAdapter());
    registerAdapter(SyncActionAdapter());
    registerAdapter(SyncEntryAdapter());
    registerAdapter(SyncItemAdapter());
  }
}
