// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVe62yJrZoRsK3FfgNy5jrkpDdUcrOrk',
    appId: '1:1095689162092:web:7c33b769c3815db8dd7749',
    messagingSenderId: '1095689162092',
    projectId: 'habit-quest-app',
    authDomain: 'habit-quest-app.firebaseapp.com',
    storageBucket: 'habit-quest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8aWCZQOHi6oeBsV_2XaU8xGk-88PxJrE',
    appId: '1:1095689162092:android:5641b59864734d6add7749',
    messagingSenderId: '1095689162092',
    projectId: 'habit-quest-app',
    storageBucket: 'habit-quest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5hcEw3sk0Vvyx4COdnQM5ZKVW2Vk-wA',
    appId: '1:1095689162092:ios:7457262c2810da45dd7749',
    messagingSenderId: '1095689162092',
    projectId: 'habit-quest-app',
    storageBucket: 'habit-quest-app.firebasestorage.app',
    androidClientId: '1095689162092-6ehs4211rc0luked9or38m9it4acq8ao.apps.googleusercontent.com',
    iosClientId: '1095689162092-9vo7vq7e6hp2qmkq8i2cdaango30t4dm.apps.googleusercontent.com',
    iosBundleId: 'com.solutech.habitquest',
  );

}