# name: "build pipeline for web release"

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#       - run: flutter pub get
#       - run: flutter build web

#       # copy file for netlify.toml
#       - name: Copy build settings to build folder
#         run: cp netlify.toml build/web/

#       # deploy application to netlify
#       - name: Deploy production to Netlify
#         uses: nwtgck/actions-netlify@v3.0
#         with:
#           publish-dir: "./build/web"
#           production-branch: master
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           deploy-message: "Deploy from GitHub Actions"
#           enable-pull-request-comment: false
#           enable-commit-comment: true
#           overwrites-pull-request-comment: false
#           production-deploy: true
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         timeout-minutes: 1
